### PR TITLE
Various pipeline fixes

### PR DESCRIPTION
**Pull request by gregvonkuster**
@ewafula This PR include the following fixes
- typo bug fixes for each of the pipelines intriduced yesterday
- Added missing cap3 and hmmsearch entries in the plantTribes.config needed by the AssemblyPostPorcesser pipeline
- Added your pasta enhancement for error checking to another appropriate code section in the PhylogenomicsAnalysis pipeline.

I'll perform more in-depth testing and get back to you shortly.

### CODE REVIEW

**Comment by ewafula** [comment]
Sure, Greg. Thanks!

**Comment by gregvonkuster** [comment]
@ewafula Please merge this and the additional PRs I will be submitting, but don't create another release tag until we're done with the PRs.  Thanks!

**Comment by gregvonkuster** [comment]
@ewafula My 2nd commit adds subroutines for creating new directory during pipeline runs, allowing for creating the directory only if it does not yet exist.  This fixes issues I encountered with the PhylogenomicsAnalysis pipeline when attempting to create multiple sequences and phylo trees.  In some scenarios the required directories had not been created.

**Comment by gregvonkuster** [comment]
@ewafula I am not able to get pasta to work successfully.  I'm now getting this error from the command line.
```
PASTA ERROR: PASTA is exiting because of an error:
'/home/_conda/envs/__plant_tribes_phylogenomics_analysis@_uv_/lib/python2.7/site-packages/PASTA-1.6.4-py2.7.egg/bin/mafft' not found. Please install 'mafft' and/or configure its location correctly in '/home/.pasta/pasta_tool_paths.cfg'
```
I'm considering eliminating the pasta option temporarily from the Galaxy tool wrapper for the PhylogenomicsAnalysis pipeline until we can figure out if we can make it work.

**Comment by gregvonkuster** [comment]
@ewafula I've completed my testing and I believe that with these 2 commits you can create another tagged release from which we can build.  Thanks!

**Comment by ewafula** [comment]
Greg,  PRs merged and v0.6 released.

**Comment by gregvonkuster** [comment]
Awesome!  Thanks a bunch @ewafula ;)  I will submit new conda recipes for this version of the pipelines this afternoon.

**Pull request merged**
